version: '3.3'

services:
  jenkins_master:
    build:
      context: ./master
    container_name: master
    ports:
      - 8080:8080 #web port
      - 50000:50000 #agent port
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
